//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atf.ScreenRecorder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string General_OutputDirectory {
            get {
                return ((string)(this["General_OutputDirectory"]));
            }
            set {
                this["General_OutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_RecordCursor {
            get {
                return ((bool)(this["General_RecordCursor"]));
            }
            set {
                this["General_RecordCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_MinimizeOnRecord {
            get {
                return ((bool)(this["General_MinimizeOnRecord"]));
            }
            set {
                this["General_MinimizeOnRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+C")]
        public global::System.Windows.Forms.Keys HotKeys_Cancel {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotKeys_Cancel"]));
            }
            set {
                this["HotKeys_Cancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotKeys_Global {
            get {
                return ((bool)(this["HotKeys_Global"]));
            }
            set {
                this["HotKeys_Global"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+P")]
        public global::System.Windows.Forms.Keys HotKeys_Pause {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotKeys_Pause"]));
            }
            set {
                this["HotKeys_Pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+R")]
        public global::System.Windows.Forms.Keys HotKeys_Record {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotKeys_Record"]));
            }
            set {
                this["HotKeys_Record"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Alt+S")]
        public global::System.Windows.Forms.Keys HotKeys_Stop {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotKeys_Stop"]));
            }
            set {
                this["HotKeys_Stop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle Tracking_Bounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["Tracking_Bounds"]));
            }
            set {
                this["Tracking_Bounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full")]
        public global::Atf.ScreenRecorder.Screen.TrackingType Tracking_Type {
            get {
                return ((global::Atf.ScreenRecorder.Screen.TrackingType)(this["Tracking_Type"]));
            }
            set {
                this["Tracking_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video_Compressor {
            get {
                return ((string)(this["Video_Compressor"]));
            }
            set {
                this["Video_Compressor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Video_Fps {
            get {
                return ((int)(this["Video_Fps"]));
            }
            set {
                this["Video_Fps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int Video_Quality {
            get {
                return ((int)(this["Video_Quality"]));
            }
            set {
                this["Video_Quality"] = value;
            }
        }
    }
}
