//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by screenshot.rc
//
#define IDS_DDERR_DIRECTDRAWALREADYCREATED 101
#define IDS_DDERR_EXCEPTION             102
#define IDS_DDERR_EXCLUSIVEMODEALREADYSET 103
#define IDS_DDERR_GENERIC               104
#define IDS_DDERR_HWNDALREADYSET        105
#define IDS_DDERR_HWNDSUBCLASSED        106
#define IDS_DDERR_INCOMPATIBLEPRIMARY   107
#define IDS_DDERR_INVALIDCAPS           108
#define IDS_DDERR_INVALIDDIRECTDRAWGUID 109
#define IDS_DDERR_INVALIDOBJECT         110
#define IDS_DDERR_INVALIDPARAMS         111
#define IDS_DDERR_INVALIDPIXELFORMAT    112
#define IDS_DDERR_INVALIDRECT           113
#define IDS_DDERR_NOALPHAHW             114
#define IDS_DDERR_NOBLTHW               115
#define IDS_DDERR_NOCOOPERATIVELEVELSET 116
#define IDS_DDERR_NODIRECTDRAWHW        117
#define IDS_DDERR_NOFLIPHW              118
#define IDS_DDERR_NOOVERLAYHW           119
#define IDS_DDERR_NOTLOCKED             120
#define IDS_DDERR_OUTOFMEMORY           121
#define IDS_DDERR_OUTOFVIDEOMEMORY      122
#define IDS_DDERR_PRIMARYSURFACEALREADYEXISTS 123
#define IDS_DDERR_SURFACEBUSY           124
#define IDS_DDERR_SURFACELOST           125
#define IDS_DDERR_UNSUPPORTED           126
#define IDS_DDERR_WASSTILLDRAWING       127
#define IDS_SSERR_INVALIDARG            128
#define IDS_SSERR_NOTSUPPORTED          129

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
